{
"autoHist": [
{ "name": "95", "min": 4.75811, "max": 10.9155 },
{ "name": "98", "min": 4.64859, "max": 13.1178 },
{ "name": "99", "min": 4.56174, "max": 15.0519 },
{ "name": "99.5", "min": 4.47352, "max": 17.1428 },
{ "name": "99.9", "min": 4.25703, "max": 23.7087 },
{ "name": "99.99", "min": 3.946, "max": 68.4278 },
{ "name": "Full range", "min": 3.55578, "max": 448.426 } ],
"minValue": 3.55578,
"maxValue": 448.426,
"naxis": 4,
"naxis1": 1024,
"naxis2": 1024,
"naxis3": 1,
"crval1": 136.75,
"crval2": -1,
"crpix1": 513,
"crpix2": 513,
"cdelt1": -0.005,
"cdelt2": 0.005,
"ctype1": "GLON-CAR",
"ctype2": "GLAT-CAR",
"equinox": 2000,
"bunit": "K (Tb)",
"fname": "../cgps.fits",
"frame": 0,
"bmaj": "",
"bmin": "",
"bpa": "",
"coords": [
{"naxis": 1024,
"crval": 136.75,
"cdelt": -0.005,
"naxis": 1024,
"crpix": 513,
"ctype": "GLON-CAR",
"cunit": ""},
{"naxis": 1024,
"crval": -1,
"cdelt": 0.005,
"naxis": 1024,
"crpix": 513,
"ctype": "GLAT-CAR",
"cunit": ""},
{"naxis": 1,
"crval": 1.42041e+09,
"cdelt": 1,
"naxis": 1,
"crpix": 1,
"ctype": "FREQ",
"cunit": ""},
{"naxis": 1,
"crval": 1,
"cdelt": 1,
"naxis": 1,
"crpix": 1,
"ctype": "STOKES",
"cunit": ""} ],
"hdr": [
{ "content": "SIMPLE  =                    T / file does conform to FITS standard             "},
{ "content": "BITPIX  =                  -32 / number of bits per data pixel                  "},
{ "content": "NAXIS   =                    4 / number of data axes                            "},
{ "content": "NAXIS1  =                 1024 / length of data axis 1                          "},
{ "content": "NAXIS2  =                 1024 / length of data axis 2                          "},
{ "content": "NAXIS3  =                    1 / length of data axis 3                          "},
{ "content": "NAXIS4  =                    1 / length of data axis 4                          "},
{ "content": "EXTEND  =                    T / FITS dataset may contain extensions            "},
{ "content": "COMMENT   FITS (Flexible Image Transport System) format defined in Astronomy and"},
{ "content": "COMMENT   Astrophysics Supplement Series v44/p363, v44/p371, v73/p359, v73/p365."},
{ "content": "COMMENT   Contact the NASA Science Office of Standards and Technology for the   "},
{ "content": "COMMENT   FITS Definition document #100 and other FITS information.             "},
{ "content": "DATE-FTS= 2002-04-22         / DATE OF FITS FILE CREATION                     "},
{ "content": "OBJECT  = CGPS Mosaic MX1    / OBJECT NAME                                    "},
{ "content": "ADC_ARCH= CGPS               / DATA CENTRE ARCHIVE                            "},
{ "content": "ADC_TYPE= MOSAIC             / TYPE OF IMAGE: FIELD/MOSAIC                    "},
{ "content": "ADC_AREA= MX1                / IMAGE AREA CODE                                "},
{ "content": "IMAG_DES= 1420-MHz Stokes I  / IMAGE DESCRIPTION                              "},
{ "content": "ADC_BAND= 1420               / SPECTRAL BAND                                  "},
{ "content": "ADC_UNIT= MHz                / BAND UNITS, OR DESCRIPTOR                      "},
{ "content": "ADC_POLR= I                  / STOKES CODE, BLANK = VARIOUS                   "},
{ "content": "ADC_QUAL= image              / IMAGE-TYPE QUALIFIER                           "},
{ "content": "ORIGIN  = CGPS Consortium    / FITS WRITING INSTITUTION                       "},
{ "content": "INSTRUME= DRAO ST            / DATA ACQUISITION INSTRUMENT                    "},
{ "content": "OBSERVER= CGPS Consortium    / OBSERVER NAME/ID                               "},
{ "content": "DATE-OBS= 2020-01-01         / MEAN DATE OF OBSERVATION                       "},
{ "content": "DATE-GPS= 2002-04-21         / DATE OF RELEASE TO CGPS CONSORTIUM             "},
{ "content": "PUB_RELD= 2002-04-21         / PUBLIC RELEASE DATE                            "},
{ "content": "BUNIT   = K (Tb)             / BRIGHTNESS UNITS                               "},
{ "content": "OBSFREQ =   1.420406000000E+09 / OBSERVING FREQUENCY (HZ)                       "},
{ "content": "CTYPE1  = GLON-CAR           / X COORDINATE TYPE                              "},
{ "content": "CRVAL1  =   1.367500000000E+02 / REF. X COORD. VALUE (DEG)                      "},
{ "content": "CRPIX1  =               513.00 / REF. X PIXEL                                   "},
{ "content": "CDELT1  =       -4.9999994E-03 / DELTA X (DEG)                                  "},
{ "content": "CROTA1  =                 0.00 / X ROTATION ANGLE (DEG)                         "},
{ "content": "CTYPE2  = GLAT-CAR           / Y COORDINATE TYPE                              "},
{ "content": "CRVAL2  =  -1.000000000000E-00 / REF. Y COORD. VALUE (DEG)                      "},
{ "content": "CRPIX2  =               513.00 / REF. Y PIXEL                                   "},
{ "content": "CDELT2  =        4.9999994E-03 / DELTA Y (DEG)                                  "},
{ "content": "CROTA2  =                 0.00 / Y ROTATION ANGLE (DEG)                         "},
{ "content": "CTYPE3  = FREQ               / Z COORDINATE TYPE                              "},
{ "content": "CRVAL3  =   1.420406000000E+09 / Z REF. FREQUENCY (HZ)                          "},
{ "content": "CRPIX3  =                 1.00 / REF. Z PIXEL                                   "},
{ "content": "CDELT3  =        1.0000000E+00 / DELTA Z                                        "},
{ "content": "CROTA3  =                 0.00 / Z ROTATION ANGLE (DEG)                         "},
{ "content": "CTYPE4  = STOKES             / 4TH COORDINATE TYPE                            "},
{ "content": "CRVAL4  =   1.000000000000E+00 / REF. COORD. 1-4=I,Q,U,V                        "},
{ "content": "CRPIX4  =                 1.00 / REF. PIXEL                                     "},
{ "content": "CDELT4  =        1.0000000E+00 / DELTA COORD.                                   "},
{ "content": "CROTA4  =                 0.00 / ROTATION ANGLE (DEG)                           "},
{ "content": "DATAMIN =        3.5557790E+00 / MINIMUM PIXEL VALUE                            "},
{ "content": "DATAMAX =        4.4842599E+02 / MAXIMUM PIXEL VALUE                            "},
{ "content": "MINCOL  =                  802 / COLUMN POSITION OF MIN VALUE                   "},
{ "content": "MAXCOL  =                  620 / COLUMN POSITION OF MAX VALUE                   "},
{ "content": "MINROW  =                   15 / ROW POSITION OF MIN VALUE                      "},
{ "content": "MAXROW  =                  534 / ROW POSITION OF MAX VALUE                      "},
{ "content": "HISTORY   >                                                                     "},
{ "content": "HISTORY   ********************************************************************* "},
{ "content": "HISTORY   The data in this FITS file have been produced by the Canadian Galactic"},
{ "content": "HISTORY   Plane Survey (CGPS) Consortium. The CGPS is supported by the National "},
{ "content": "HISTORY   Research Council of Canada and the Natural Sciences and Engineering   "},
{ "content": "HISTORY   Research Council of Canada. These data are released to the public for "},
{ "content": "HISTORY   scientific research and educational purposes. The CGPS Consortium has "},
{ "content": "HISTORY   made very reasonable efforts to produce accurate data, but no warranty"},
{ "content": "HISTORY   is expressed or implied as to the suitability of the data for any     "},
{ "content": "HISTORY   particular purpose. Users are requested to include the following      "},
{ "content": "HISTORY   acknowledgement in publications making use of CGPS data:              "},
{ "content": "HISTORY   >                                                                     "},
{ "content": "HISTORY   The Canadian Galactic Plane Survey (CGPS) is a Canadian project with "},
{ "content": "HISTORY   international partners. The Dominion Radio Astrophysical Observatory  "},
{ "content": "HISTORY   is operated as a national facility by the National Research Council   "},
{ "content": "HISTORY   of Canada. The CGPS is supported by a grant from the Natural Sciences "},
{ "content": "HISTORY   and Engineering Research Council of Canada.                          "},
{ "content": "HISTORY   >                                                                     "},
{ "content": "HISTORY   General information on the CGPS may be obtained from the CGPS public  "},
{ "content": "HISTORY   web site http://www.ras.ucalgary.ca/CGPS and queries regarding the    "},
{ "content": "HISTORY   CGPS or its data may be addressed to cgps@ras.ucalgary.ca .           "},
{ "content": "HISTORY   >                                                                     "},
{ "content": "HISTORY   More detailed comments regarding the data in this FITS file may be    "},
{ "content": "HISTORY   found in a readme file which accompanies this data release.         "},
{ "content": "HISTORY   ********************************************************************* "},
{ "content": "HISTORY   >                                                                     "},
{ "content": "HISTORY   The file definition included the comment:                             "},
{ "content": "HISTORY   MX1 C21 MOSAIC                                                        "},
{ "content": "HISTORY   >                                                                     "},
{ "content": "HISTORY   >                                                                     "},
{ "content": "HISTORY   There are spoke-type artifacts radiating from the location of the sour"},
{ "content": "HISTORY   ce at                                                                 "},
{ "content": "HISTORY   (l,b) = (136.21,-0.90).                                               "},
{ "content": "CHECKSUM= XhAbYg5ZXgAaXg3Y   / encoded HDU checksum updated on 22/04/02       "},
{ "content": "DATASUM = 1672981712         / data unit checksum updated on 22/04/02         "},
{ "content": "END                                                                             "} ],
"frameTitle": "Frequency 1.42041 GHz   Stokes I",
"tileSize": 512
}