{
"autoHist": [
{ "name": "95", "min": -1.30866, "max": 1.83076 },
{ "name": "98", "min": -1.49494, "max": 1.97587 },
{ "name": "99", "min": -2.15952, "max": 4.97701 },
{ "name": "99.5", "min": -2.23663, "max": 28.8936 },
{ "name": "99.9", "min": -2.36471, "max": 177.751 },
{ "name": "99.99", "min": -3.16342, "max": 957.27 },
{ "name": "Full range", "min": -3.23157, "max": 1442.34 } ],
"minValue": -3.23157,
"maxValue": 1442.34,
"naxis": 3,
"naxis1": 200,
"naxis2": 200,
"naxis3": 4,
"crval1": 182.631,
"crval2": 39.3963,
"crpix1": 420,
"crpix2": 424.5,
"cdelt1": 1,
"cdelt2": 1,
"ctype1": "RA---TAN",
"ctype2": "DEC--TAN",
"equinox": 2000,
"bunit": "",
"fname": "../test.fits",
"frame": 0,
"bmaj": "",
"bmin": "",
"bpa": "",
"coords": [
{"naxis": 200,
"crval": 182.631,
"cdelt": 1,
"naxis": 200,
"crpix": 420,
"ctype": "RA---TAN",
"cunit": ""},
{"naxis": 200,
"crval": 39.3963,
"cdelt": 1,
"naxis": 200,
"crpix": 424.5,
"ctype": "DEC--TAN",
"cunit": ""},
{"naxis": 4,
"crval": 0,
"cdelt": 1,
"naxis": 4,
"crpix": 0,
"ctype": "GROUP_NUMBER",
"cunit": ""} ],
"hdr": [
{ "content": "SIMPLE  =                    T / file does conform to FITS standard             "},
{ "content": "BITPIX  =                  -32 / number of bits per data pixel                  "},
{ "content": "NAXIS   =                    3 / number of data axes                            "},
{ "content": "NAXIS1  =                  200 / length of data axis 1                          "},
{ "content": "NAXIS2  =                  200 / length of data axis 2                          "},
{ "content": "NAXIS3  =                    4 / length of data axis 3                          "},
{ "content": "EXTEND  =                    T / FITS dataset may contain extensions            "},
{ "content": "COMMENT   FITS (Flexible Image Transport System) format is defined in Astronomy"},
{ "content": "COMMENT   and Astrophysics, volume 376, page 359; bibcode: 2001A&A...376..359H "},
{ "content": "BSCALE  =                1.0E0 / REAL = TAPE*BSCALE + BZERO                     "},
{ "content": "BZERO   =                0.0E0 /                                                "},
{ "content": "OPSIZE  =                 2112 / PSIZE of original image                        "},
{ "content": "ORIGIN  = STScI-STSDAS       / Fitsio version 21-Feb-1996                     "},
{ "content": "FITSDATE= 2004-01-09         / Date FITS file was created                     "},
{ "content": "FILENAME= u5780205r_cvt.c0h  / Original filename                              "},
{ "content": "ALLG-MAX=           3.777701E3 / Data max in all groups                         "},
{ "content": "ALLG-MIN=          -7.319537E1 / Data min in all groups                         "},
{ "content": "ODATTYPE= FLOATING           / Original datatype: Single precision real       "},
{ "content": "SDASMGNU=                    4 / Number of groups in original image             "},
{ "content": "CRVAL1  =       182.6311886308                                                  "},
{ "content": "CRVAL2  =       39.39633673411                                                  "},
{ "content": "CRPIX1  =                 420.                                                  "},
{ "content": "CRPIX2  =                424.5                                                  "},
{ "content": "CD1_1   =         -1.067040E-6                                                  "},
{ "content": "CD1_2   =         -1.259580E-5                                                  "},
{ "content": "CD2_1   =         -1.260160E-5                                                  "},
{ "content": "CD2_2   =          1.066550E-6                                                  "},
{ "content": "DATAMIN =          -7.319537E1 / DATA MIN                                       "},
{ "content": "DATAMAX =           3.777701E3 / DATA MAX                                       "},
{ "content": "MIR_REVR=                    T                                                  "},
{ "content": "ORIENTAT=               -85.16                                                  "},
{ "content": "FILLCNT =                    0                                                  "},
{ "content": "ERRCNT  =                    0                                                  "},
{ "content": "FPKTTIME=         51229.798574                                                  "},
{ "content": "LPKTTIME=         51229.798742                                                  "},
{ "content": "CTYPE1  = RA---TAN                                                            "},
{ "content": "CTYPE2  = DEC--TAN                                                            "},
{ "content": "DETECTOR=                    1                                                  "},
{ "content": "DEZERO  =             316.6452                                                  "},
{ "content": "BIASEVEN=             316.6715                                                  "},
{ "content": "BIASODD =             316.6189                                                  "},
{ "content": "GOODMIN =            -5.064006                                                  "},
{ "content": "GOODMAX =              2552.17                                                  "},
{ "content": "DATAMEAN=            0.4182382                                                  "},
{ "content": "GPIXELS =               632387                                                  "},
{ "content": "SOFTERRS=                    0                                                  "},
{ "content": "CALIBDEF=                 1466                                                  "},
{ "content": "STATICD =                    0                                                  "},
{ "content": "ATODSAT =                   16                                                  "},
{ "content": "DATALOST=                    0                                                  "},
{ "content": "BADPIXEL=                    0                                                  "},
{ "content": "OVERLAP =                    0                                                  "},
{ "content": "PHOTMODE= WFPC2,1,A2D7,LRF#4877.0,,CAL                                        "},
{ "content": "PHOTFLAM=         3.447460E-16                                                  "},
{ "content": "PHOTZPT =                -21.1                                                  "},
{ "content": "PHOTPLAM=             4884.258                                                  "},
{ "content": "PHOTBW  =             20.20996                                                  "},
{ "content": "MEDIAN  =            -0.175651                                                  "},
{ "content": "MEDSHADO=            -0.121681                                                  "},
{ "content": "HISTWIDE=             1.033711                                                  "},
{ "content": "SKEWNESS=            -1.983727                                                  "},
{ "content": "MEANC10 =              0.12958                                                  "},
{ "content": "MEANC25 =            0.3129676                                                  "},
{ "content": "MEANC50 =            0.4577668                                                  "},
{ "content": "MEANC100=            0.3916293                                                  "},
{ "content": "MEANC200=            0.3115222                                                  "},
{ "content": "MEANC300=            0.3295493                                                  "},
{ "content": "BACKGRND=           -0.3676353                                                  "},
{ "content": "ORIGIN  = NOAO-IRAF FITS Image Kernel December 2001 / FITS file originator    "},
{ "content": "DATE    = 2004-01-09T03:26:36                                                 "},
{ "content": "IRAF-TLM= 03:26:36 (09/01/2004)                                               "},
{ "content": "FILETYPE= SCI                / type of data found in data file                "},
{ "content": "                                                                                "},
{ "content": "TELESCOP= HST                / telescope used to acquire data                 "},
{ "content": "INSTRUME= WFPC2              / identifier for instrument used to acquire data "},
{ "content": "EQUINOX =               2000.0 / equinox of celestial coord. system             "},
{ "content": "                                                                                "},
{ "content": "              / WFPC-II DATA DESCRIPTOR KEYWORDS                                "},
{ "content": "                                                                                "},
{ "content": "ROOTNAME= u5780205r             / rootname of the observation set             "},
{ "content": "PROCTIME=   5.301314019676E+04 / Pipeline processing time (MJD)                 "},
{ "content": "OPUS_VER= OPUS 14.5a         / OPUS software system version number            "},
{ "content": "CAL_VER =                          / CALWP2 code version                      "},
{ "content": "                                                                                "},
{ "content": "              / SCIENCE INSTRUMENT CONFIGURATION                                "},
{ "content": "                                                                                "},
{ "content": "MODE    = FULL               / instr. mode: FULL (full res.), AREA (area int.)"},
{ "content": "SERIALS = OFF                / serial clocks: ON, OFF                         "},
{ "content": "                                                                                "},
{ "content": "              / IMAGE TYPE CHARACTERISTICS                                      "},
{ "content": "                                                                                "},
{ "content": "IMAGETYP= EXT                / DARK/BIAS/IFLAT/UFLAT/VFLAT/KSPOT/EXT/ECAL     "},
{ "content": "CDBSFILE= NO                 / GENERIC/BIAS/DARK/PREF/FLAT/MASK/ATOD/NO       "},
{ "content": "PKTFMT  =                   96 / packet format code                             "},
{ "content": "                                                                                "},
{ "content": "              / FILTER CONFIGURATION                                            "},
{ "content": "                                                                                "},
{ "content": "FILTNAM1= FR533P15           / first filter name                              "},
{ "content": "FILTNAM2=                    / second filter name                             "},
{ "content": "FILTER1 =                   69 / first filter number (0-48)                     "},
{ "content": "FILTER2 =                    0 / second filter number (0-48)                    "},
{ "content": "FILTROT =                 15.0 / partial filter rotation angle (degrees)        "},
{ "content": "LRFWAVE =          4877.000000 / linear ramp filter wavelength                  "},
{ "content": "                                                                                "},
{ "content": "              / INSTRUMENT STATUS USED IN DATA PROCESSING                       "},
{ "content": "                                                                                "},
{ "content": "UCH1CJTM=             -88.2569 / TEC cold junction #1 temperature (Celsius)     "},
{ "content": "UCH2CJTM=             -88.6697 / TEC cold junction #2 temperature (Celsius)     "},
{ "content": "UCH3CJTM=             -88.3028 / TEC cold junction #3 temperature (Celsius)     "},
{ "content": "UCH4CJTM=             -88.7671 / TEC cold junction #4 temperature (Celsius)     "},
{ "content": "UBAY3TMP=              13.2302 / bay 3 A1 temperature (deg C)                   "},
{ "content": "KSPOTS  = OFF                / Status of Kelsall spot lamps: ON, OFF          "},
{ "content": "SHUTTER = A                  / Shutter in place at beginning of the exposure  "},
{ "content": "ATODGAIN=                  7.0 / Analog to Digital Gain (Electrons/DN)          "},
{ "content": "                                                                                "},
{ "content": "              / RSDP CONTROL KEYWORDS                                           "},
{ "content": "                                                                                "},
{ "content": "MASKCORR= COMPLETE           / Do mask correction: PERFORM, OMIT, COMPLETE    "},
{ "content": "ATODCORR= COMPLETE           / Do A-to-D correction: PERFORM, OMIT, COMPLETE  "},
{ "content": "BLEVCORR= COMPLETE           / Do bias level correction                       "},
{ "content": "BIASCORR= COMPLETE           / Do bias correction: PERFORM, OMIT, COMPLETE    "},
{ "content": "DARKCORR= COMPLETE           / Do dark correction: PERFORM, OMIT, COMPLETE    "},
{ "content": "FLATCORR= SKIPPED            / Do flat field correction                       "},
{ "content": "SHADCORR= OMIT               / Do shaded shutter correction                   "},
{ "content": "DOSATMAP= OMIT               / Output saturated pixel map                     "},
{ "content": "DOPHOTOM= COMPLETE           / Fill photometry keywords                       "},
{ "content": "DOHISTOS= OMIT               / Make histograms: PERFORM, OMIT, COMPLETE       "},
{ "content": "OUTDTYPE= REAL               / Output image datatype: REAL, LONG, SHORT       "},
{ "content": "                                                                                "},
{ "content": "              / CALIBRATION REFERENCE FILES                                     "},
{ "content": "                                                                                "},
{ "content": "MASKFILE= uref$f8213081u.r0h      / name of the input DQF of known bad pixels "},
{ "content": "ATODFILE= uref$dbu1405iu.r1h      / name of the A-to-D conversion file        "},
{ "content": "BLEVFILE= ucal$u5780205r.x0h      / Engineering file with extended register da"},
{ "content": "BLEVDFIL= ucal$u5780205r.q1h      / Engineering file DQF                      "},
{ "content": "BIASFILE= uref$j9a1612mu.r2h      / name of the bias frame reference file     "},
{ "content": "BIASDFIL= uref$j9a1612mu.b2h      / name of the bias frame reference DQF      "},
{ "content": "DARKFILE= uref$j2g1549cu.r3h      / name of the dark reference file           "},
{ "content": "DARKDFIL= uref$j2g1549cu.b3h      / name of the dark reference DQF            "},
{ "content": "FLATFILE= uref$f4i1559cu.r4h      / name of the flat field reference file     "},
{ "content": "FLATDFIL= uref$f4i1559cu.b4h      / name of the flat field reference DQF      "},
{ "content": "SHADFILE= uref$e371355eu.r5h      / name of the reference file for shutter sha"},
{ "content": "PHOTTAB = u5780205r_c3t.fits      / name of the photometry calibration table  "},
{ "content": "GRAPHTAB= mtab$n9i1408hm_tmg.fits / the HST graph table                       "},
{ "content": "COMPTAB = mtab$nc809508m_tmc.fits / the HST components table                  "},
{ "content": "                                                                                "},
{ "content": "              / DEFAULT KEYWORDS SET BY STSCI                                   "},
{ "content": "                                                                                "},
{ "content": "SATURATE=                 4095 / Data value at which saturation occurs          "},
{ "content": "USCALE  =                  1.0 / Scale factor for output image                  "},
{ "content": "UZERO   =                  0.0 / Zero point for output image                    "},
{ "content": "                                                                                "},
{ "content": "              / READOUT DURATION INFORMATION                                    "},
{ "content": "                                                                                "},
{ "content": "READTIME=                  464 / Length of time for CCD readout in clock ticks  "},
{ "content": "                                                                                "},
{ "content": "              / PLANETARY SCIENCE KEYWORDS                                      "},
{ "content": "                                                                                "},
{ "content": "PA_V3   =            49.936909 / position angle of V3-axis of HST (deg)         "},
{ "content": "RA_SUN  =   3.337194516616E+02 / right ascension of the sun (deg)               "},
{ "content": "DEC_SUN =  -1.086675160382E+01 / declination of the sun (deg)                   "},
{ "content": "EQNX_SUN=               2000.0 / equinox of the sun                             "},
{ "content": "MTFLAG  =                    F / moving target flag; T if it is a moving target "},
{ "content": "EQRADTRG=             0.000000 / equatorial radius of target (km)               "},
{ "content": "FLATNTRG=             0.000000 / flattening of target                           "},
{ "content": "NPDECTRG=             0.000000 / north pole declination of target (deg)         "},
{ "content": "NPRATRG =             0.000000 / north pole right ascension of target (deg)     "},
{ "content": "ROTRTTRG=             0.000000 / rotation rate of target                        "},
{ "content": "LONGPMER=             0.000000 / longitude of prime meridian (deg)              "},
{ "content": "EPLONGPM=             0.000000 / epoch of longitude of prime meridian (sec)     "},
{ "content": "SURFLATD=             0.000000 / surface feature latitude (deg)                 "},
{ "content": "SURFLONG=             0.000000 / surface feature longitude (deg)                "},
{ "content": "SURFALTD=             0.000000 / surface feature altitude (km)                  "},
{ "content": "                                                                                "},
{ "content": "              / PODPS FILL VALUES                                               "},
{ "content": "                                                                                "},
{ "content": "PODPSFF =                    0 / 0=(no  podps fill); 1=(podps fill present)     "},
{ "content": "STDCFFF =                    0 / 0=(no st dcf fill); 1=(st dcf fill present)    "},
{ "content": "STDCFFP = 0x5569             / st dcf fill pattern (hex)                      "},
{ "content": "RSDPFILL=                 -100 / bad data fill value for calibrated images      "},
{ "content": "                                                                                "},
{ "content": "              / EXPOSURE TIME AND RELATED INFORMATION                           "},
{ "content": "                                                                                "},
{ "content": "UEXPODUR=                  300 / commanded duration of exposure (sec)           "},
{ "content": "NSHUTA17=                    1 / Number of AP17 shutter B closes                "},
{ "content": "DARKTIME=   3.000000000000E+02 / Dark time (seconds)                            "},
{ "content": "UEXPOTIM=                16880 / Major frame pulse time preceding exposure start"},
{ "content": "PSTRTIME= 1999.051:19:08:37  / predicted obs. start time (yyyy.ddd:hh:mm:ss)  "},
{ "content": "PSTPTIME= 1999.051:19:16:37  / predicted obs. stop time (yyyy.ddd:hh:mm:ss)   "},
{ "content": "                                                                                "},
{ "content": "              / EXPOSURE INFORMATION                                            "},
{ "content": "                                                                                "},
{ "content": "SUNANGLE=           141.618347 / angle between sun and V1 axis                  "},
{ "content": "MOONANGL=           126.698997 / angle between moon and V1 axis                 "},
{ "content": "SUN_ALT =           -31.523479 / altitude of the sun above Earths limb         "},
{ "content": "FGSLOCK = FINE               / commanded FGS lock (FINE,COARSE,GYROS,UNKNOWN) "},
{ "content": "                                                                                "},
{ "content": "DATE-OBS= 1999-02-20         / UT date of start of observation (yyyy-mm-dd)   "},
{ "content": "TIME-OBS= 19:03:13           / UT time of start of observation (hh:mm:ss)     "},
{ "content": "EXPSTART=   5.122979390428E+04 / exposure start time (Modified Julian Date)     "},
{ "content": "EXPEND  =   5.122979737650E+04 / exposure end time (Modified Julian Date)       "},
{ "content": "EXPTIME =   3.000000000000E+02 / exposure duration (seconds)--calculated        "},
{ "content": "EXPFLAG = NORMAL             / Exposure interruption indicator                "},
{ "content": "                                                                                "},
{ "content": "              / TARGET & PROPOSAL ID                                            "},
{ "content": "TARGNAME= NGC4151                        / proposers target name             "},
{ "content": "RA_TARG =   1.826355000000E+02 / right ascension of the target (deg) (J2000)    "},
{ "content": "DEC_TARG=   3.940576666667E+01 / declination of the target (deg) (J2000)        "},
{ "content": "ECL_LONG=           164.096619 / ecliptic longitude of the target (deg) (J2000) "},
{ "content": "ECL_LAT =            36.623709 / ecliptic latitude of the target (deg) (J2000)  "},
{ "content": "GAL_LONG=           155.079532 / galactic longitude of the target (deg) (J2000) "},
{ "content": "GAL_LAT =            75.062679 / galactic latitude of the target (deg) (J2000)  "},
{ "content": "                                                                                "},
{ "content": "PROPOSID=                 8019 / PEP proposal identifier                        "},
{ "content": "PEP_EXPO= 02-030             / PEP exposure identifier including sequence     "},
{ "content": "LINENUM = 02.030             / PEP proposal line number                       "},
{ "content": "SEQLINE =                    / PEP line number of defined sequence            "},
{ "content": "SEQNAME =                    / PEP define/use sequence name                   "},
{ "content": "HISTORY   MASKFILE=uref$f8213081u.r0h  MASKCORR=COMPLETED                       "},
{ "content": "HISTORY   PEDIGREE=INFLIGHT 01/01/1994 - 15/05/1995                             "},
{ "content": "HISTORY   DESCRIP=STATIC MASK - INCLUDES CHARGE TRANSFER TRAPS                  "},
{ "content": "HISTORY   BIASFILE=uref$j9a1612mu.r2h  BIASCORR=COMPLETED                       "},
{ "content": "HISTORY   PEDIGREE=INFLIGHT 29/08/98 - 21/08/99                                 "},
{ "content": "HISTORY   DESCRIP=not significantly different from j6e16008u.                   "},
{ "content": "HISTORY   DARKFILE=uref$j2g1549cu.r3h  DARKCORR=COMPLETED                       "},
{ "content": "HISTORY   PEDIGREE=INFLIGHT 16/02/1999 - 16/02/1999                             "},
{ "content": "HISTORY   DESCRIP=Pipeline dark: 120 frame superdark with hotpixels from        "},
{ "content": "HISTORY   16/02/99                                                              "},
{ "content": "HISTORY   FLATFILE=uref$f4i1559cu.r4h  FLATCORR=SKIPPED                         "},
{ "content": "HISTORY   PEDIGREE=DUMMY  18/04/1995                                            "},
{ "content": "HISTORY   DESCRIP=All pixels set to value of 1. Not flat-fielded.               "},
{ "content": "HISTORY   PC1: bias jump level ~0.100 DN.                                       "},
{ "content": "HISTORY   The following throughput tables were used:                            "},
{ "content": "HISTORY   crotacomp$hst_ota_007_syn.fits, crwfpc2comp$wfpc2_optics_006_syn.fits,"},
{ "content": "HISTORY   crwfpc2comp$wfpc2_lrf_004_syn.fits[wave#],                            "},
{ "content": "HISTORY   crwfpc2comp$wfpc2_dqepc1_005_syn.fits,                                "},
{ "content": "HISTORY   crwfpc2comp$wfpc2_a2d7pc1_004_syn.fits,                               "},
{ "content": "HISTORY   crwfpc2comp$wfpc2_flatpc1_003_syn.fits                                "},
{ "content": "HISTORY   The following throughput tables were used:                            "},
{ "content": "HISTORY   crotacomp$hst_ota_007_syn.fits, crwfpc2comp$wfpc2_optics_006_syn.fits,"},
{ "content": "HISTORY   crwfpc2comp$wfpc2_lrf_004_syn.fits[wave#],                            "},
{ "content": "HISTORY   crwfpc2comp$wfpc2_dqewfc2_005_syn.fits,                               "},
{ "content": "HISTORY   crwfpc2comp$wfpc2_a2d7wf2_004_syn.fits,                               "},
{ "content": "HISTORY   crwfpc2comp$wfpc2_flatwf2_003_syn.fits                                "},
{ "content": "HISTORY   The following throughput tables were used:                            "},
{ "content": "HISTORY   crotacomp$hst_ota_007_syn.fits, crwfpc2comp$wfpc2_optics_006_syn.fits,"},
{ "content": "HISTORY   crwfpc2comp$wfpc2_lrf_004_syn.fits[wave#],                            "},
{ "content": "HISTORY   crwfpc2comp$wfpc2_dqewfc3_005_syn.fits,                               "},
{ "content": "HISTORY   crwfpc2comp$wfpc2_a2d7wf3_004_syn.fits,                               "},
{ "content": "HISTORY   crwfpc2comp$wfpc2_flatwf3_003_syn.fits                                "},
{ "content": "HISTORY   The following throughput tables were used:                            "},
{ "content": "HISTORY   crotacomp$hst_ota_007_syn.fits, crwfpc2comp$wfpc2_optics_006_syn.fits,"},
{ "content": "HISTORY   crwfpc2comp$wfpc2_lrf_004_syn.fits[wave#],                            "},
{ "content": "HISTORY   crwfpc2comp$wfpc2_dqewfc4_005_syn.fits,                               "},
{ "content": "HISTORY   crwfpc2comp$wfpc2_a2d7wf4_004_syn.fits,                               "},
{ "content": "HISTORY   crwfpc2comp$wfpc2_flatwf4_003_syn.fits                                "},
{ "content": "CTYPE3  = GROUP_NUMBER       / Extra dimension axis name                      "},
{ "content": "CD3_3   =                    1 /                                                "},
{ "content": "CD3_1   =                    0 /                                                "},
{ "content": "CD1_3   =                    0 /                                                "},
{ "content": "CD2_3   =                    0 /                                                "},
{ "content": "CD3_2   =                    0 /                                                "},
{ "content": "END                                                                             "} ],
"frameTitle": "GROUP_NUMBER 1",
"tileSize": 512
}